// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RBridge")>]
[<assembly: AssemblyCompanyAttribute("University of Cambridge")>]
[<assembly: AssemblyProductAttribute("RBridge")>]
[<assembly: AssemblyDescriptionAttribute("A slim F# bridge for R.")>]
[<assembly: AssemblyVersionAttribute("1.0.4")>]
[<assembly: AssemblyFileVersionAttribute("1.0.4")>]
do ()

