name: Build Native Libraries

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-native:
    strategy:
      matrix:
        r-version: [ '4.5.0' ]
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [ x64, arm64 ]
        exclude:
        - os: macos-latest
          arch: x64
        - os: windows-latest
          arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Download R source headers
        shell: bash
        working-directory: src/r-bridge/RBridge/native
        run: |
          curl -L https://cran.r-project.org/src/base/R-4/R-${{ matrix.r-version }}.tar.gz -o R.tar.gz
          mkdir r-headers
          tar -xzf R.tar.gz --strip-components=2 -C r-headers R-${{ matrix.r-version }}/include
          tar -xzf R.tar.gz --strip-components=3 -C r-headers R-${{ matrix.r-version }}/src/include

      - uses: r-lib/actions/setup-r@v2
        name: Setup R
        with:
          r-version: ${{ matrix.r-version }}

      - name: Set R_HOME environment variable
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
                mkdir -p ~/.local/lib/R
                echo "R_LIBS_USER=~/.local/lib/R" >> "$GITHUB_ENV"
                echo "R_HOME=$(R RHOME)" >> "$GITHUB_ENV"
          elif [ "$RUNNER_OS" == "macOS" ]; then
                echo "R_HOME=$(R RHOME)" >> "$GITHUB_ENV"
          elif [ "$RUNNER_OS" == "Windows" ]; then
                echo "R_HOME=$(R RHOME)" >> "$GITHUB_ENV"
          else
                echo "$RUNNER_OS not supported"
                exit 1
          fi
        shell: bash

      - name: Build native library
        working-directory: src/r-bridge/RBridge/native
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            clang -dynamiclib native_api.c \
              -o librbridge-native.dylib \
              -I"r-headers" -I"$R_HOME/include" -L"$R_HOME/lib" -lR -DR_INTERFACE_PTRS
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            gcc -shared -fPIC native_api.c \
              -o librbridge-native.so \
              -I"r-headers" -I"$R_HOME/include" -L"$R_HOME/lib" -lR -DR_INTERFACE_PTRS
          else
            WIN_HEADERS=$(cygpath -u "${GITHUB_WORKSPACE}/src/r-bridge/RBridge/native/r-headers")
            gcc -shared -fPIC native_api.c \
              -o rbridge-native.dll \
              -I"$WIN_HEADERS" \
              -L"/c/rtools42/usr/lib" \
              -lR \
              -DR_INTERFACE_PTRS
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            src/r-bridge/RBridge/native/*.dll
            src/r-bridge/RBridge/native/*.so
            src/r-bridge/RBridge/native/*.dylib